### ISSUE TITLE
asofJoin()  requires name of timpestamp column names to match

### ISSUE THREAD

**Issue by ghormann** [databrickslabs/tempo#390]
When trying to use `asofJoin()` on two TSDF records with different time series column names an exception is raised.  I'm not sure if this is a considered a bug or a feature, but given that TSDF knows the column name of each TSDF  object, it seems like it should be smart enough to execute the join.

# Example
* tsdf_state has time column 'ts'
* tsdf_validate has time column 'EndTime'
* Running `asofJoin()` results in an error as it is using `EndTime` on tsdf_state

![image](https://github.com/databrickslabs/tempo/assets/24968726/1466eb67-be4c-41c1-a7d4-5ed44e193180)

# Workaround
If I make sure the time column is the same for both TSDF records it appears to work as expected. _(Here column 'ts' is created as a copy of EndTime before creating tsdf_validate)._ 

![image](https://github.com/databrickslabs/tempo/assets/24968726/4768cb5f-56d4-4630-bdad-ee4bcfdec903)

**Comment by tnixon** [comment]
Thanks for raising this to us, @ghormann - definitely a frustrating issue. I believe this should be fixed in the upcoming v0.2 version, but we'll be sure to double check. Maybe it makes sense to get a quick fix in here before that comes out.

**Comment by R7L208** [comment]
## Triage — March 2026

**Status**: Not resolved — actually **more restrictive** on `v0.2-integration`. The v0.2 `as_of_join` requires both left and right TSDFs to have matching `ts_schema` (same timestamp column name AND same series ID columns). In v0.1, mismatched timestamp column names already caused issues; v0.2 enforces schema compatibility even more strictly.

**Jobs to be done**:
- Allow `as_of_join` to work when left and right TSDFs have different timestamp column names (e.g., `left.ts_col="event_time"`, `right.ts_col="trade_time"`)
- Add a column-mapping parameter or automatic rename/alignment step

**Effort estimate**: 🟢 Small (1-2 days)

**Closure path**: Implement timestamp column remapping in `as_of_join`. This is a usability improvement that removes an unnecessary constraint.
